- name: Deploy Logisticks App
  hosts: all
  become: yes  # Ensures privileged access if needed for Docker commands
  tasks:
    - name: Pull Docker Images
      docker_compose:
        project_src: ../
        pull: yes

    - name: Deploy Containers
      docker_compose:
        project_src: ../
        state: present
