- name: Deploy Logisticks Backend and Frontend
  hosts: any
  become: yes  # Ensure privileged access for Docker operations
  tasks:
    - name: Remove old backend container
      docker_container:
        name: logisticks-backend
        state: absent
        force_kill: yes

    - name: Deploy Backend Service
      docker_container:
        name: logisticks-backend
        image: keshavchandak/logisticks-backend
        state: started
        ports:
          - "8088:8088"  # Map backend service to host
        restart_policy: always
        detach: yes

    - name: Remove old frontend container
      docker_container:
        name: logisticks-frontend
        state: absent
        force_kill: yes

    - name: Deploy Frontend Service
      docker_container:
        name: logisticks-frontend
        image: keshavchandak/logisticks-frontend
        state: started
        ports:
          - "5173:5173"  # Map frontend service to host
        restart_policy: always
        detach: yes
