version: '3.8'
services:
  backend:
    build:
      context: ./backend
    image: ${BACKEND_IMAGE}
    ports:
      - "8088:8088"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: ${FRONTEND_IMAGE}
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
