apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: keshavchandak/logisticks-backend:latest
        ports:
        - containerPort: 8088
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/logisticks
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: KeshavC@2003
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
  type: ClusterIP
