# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - name: mysql
#           image: mysql:5.7
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: logisticks-secrets
#                   key: MYSQL_ROOT_PASSWORD
#             - name: MYSQL_DATABASE
#               valueFrom:
#                 configMapKeyRef:
#                   name: logisticks-config
#                   key: MYSQL_DATABASE
#           ports:
#             - containerPort: 3306
#           volumeMounts:
#             - name: mysql-data
#               mountPath: /var/lib/mysql
#   volumes:
#     - name: mysql-data
#       emptyDir: {}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service
# spec:
#   selector:
#     app: mysql
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: logisticks-backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: logisticks-backend
#   template:
#     metadata:
#       labels:
#         app: logisticks-backend
#     spec:
#       containers:
#         - name: logisticks-backend
#           image: "{{ lookup('env', 'BACKEND_IMAGE') }}"
#           env:
#             - name: SPRING_DATASOURCE_URL
#               valueFrom:
#                 configMapKeyRef:
#                   name: logisticks-config
#                   key: SPRING_DATASOURCE_URL
#             - name: SPRING_DATASOURCE_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: logisticks-secrets
#                   key: SPRING_DATASOURCE_PASSWORD
#             - name: MYSQL_DATABASE
#               valueFrom:
#                 configMapKeyRef:
#                   name: logisticks-config
#                   key: MYSQL_DATABASE
#           ports:
#             - containerPort: 8088

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: logisticks-backend-service
# spec:
#   selector:
#     app: logisticks-backend
#   ports:
#     - protocol: TCP
#       port: 8088
#       targetPort: 8088

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: logisticks-frontend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: logisticks-frontend
#   template:
#     metadata:
#       labels:
#         app: logisticks-frontend
#     spec:
#       containers:
#         - name: logisticks-frontend
#           image: "{{ lookup('env', 'FRONTEND_IMAGE') }}"
#           ports:
#             - containerPort: 5173

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: logisticks-frontend-service
# spec:
#   selector:
#     app: logisticks-frontend
#   ports:
#     - protocol: TCP
#       port: 5173
#       targetPort: 5173
